openapi: 3.0.3
info:
  title: Daisy
  description: "A set of REST-ful APIs to control & manage Daisy's component"
  version: 0.0.1
paths:
  /datasets/{name}:
    post:
      description: Build the dataset and create a temporary view to be used by others if necessary
      summary: Build the dataset and create a temporary view to be used by others if necessary
      tags:
        - dataset
      operationId: "buildDataset"
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
        - name: createTableOrViewPreference
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/CreateTableOrViewPreference'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parameters'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildDatasetResponse'
          description: Created
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AbnormalResponse'
          description: Internal Server Error
  /ml/{name}/predict:
    post:
      description: Get prediction from the model of the machine learning which has the given name
      summary: Get prediction from the model of the machine learning which has the given name
      tags:
        - ml
      operationId: "getPrediction"
      parameters:
        - name: modelId
          in: query
          required: true
          schema:
            type: string
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
                description: The prediction in JSON format
          description: OK
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AbnormalResponse'
          description:  Internal Server Error
  /ml/{name}/train:
    post:
      description: ""
      summary: Build & train the model of the machine learning which has the given name
      tags:
        - ml
      operationId: "trainModel"
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parameters'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainingResponse'
          description: OK
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AbnormalResponse'
          description: Internal Server Error
  /pipelines/{name}/trigger:
    post:
      description: Trigger the pipeline which has the given name
      summary: Trigger the pipeline which has the given name
      tags:
        - pipelines
      operationId: "triggerPipeline"
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parameters'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TriggerPipelineResponse'
          description: OK
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AbnormalResponse'
          description: Internal Server Error
components:
  schemas:
    AbnormalResponse:
      type: object
      required:
        - throwable
        - stackFrame
      properties:
        throwable:
          type: string
        stackFrame:
          type: string
    BuildDatasetResponse:
      type: object
      required:
        - createdTable
        - createdView
      properties:
        createdTable:
          type: boolean
        createdView:
          type: boolean
        viewType:
          type: string
          enum:
            - GLOBAL
            - LOCAL
    CreateTableOrViewPreference:
      type: string
      enum:
        - CREATE_GLOBAL_VIEW
        - CREATE_LOCAL_VIEW
        - CREATE_OR_REPLACE_GLOBAL_VIEW
        - CREATE_OR_REPLACE_LOCAL_VIEW
        - CREATE_TABLE_APPEND
        - CREATE_TABLE_ERROR_IF_EXISTS
        - CREATE_TABLE_IGNORE_IF_EXISTS
        - CREATE_TABLE_OVERWRITE
    Parameters:
      type: object
      additionalProperties: true
    TriggerPipelineResponse:
      type: object
      required:
        - isStreaming
      properties:
        isStreaming:
          type: boolean
        streamingQueryId:
          type: string
          format: uuid
    TrainingResponse:
      type: object
      required:
        - modelId
        - modelUri
      properties:
        modelId:
          type: string
        modelUri:
          type: string
