cxf:
  jaxrs:
    component-scan: true
    component-scan-packages: io.openenterprise.daisy.rs
  servlet:
    enabled: true

daisy:
  aws:
    s3:
      bucket: daisy
  spark:
    streaming:
      checkpoint-location: spark-checkpoints